import esbuild from 'esbuild';
import process from 'process';
import builtins from 'builtin-modules';
import { sassPlugin } from '@shellscape/esbuild-sass-plugin';

const banner =
  `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === 'production');

const context = await esbuild.context({
  banner: {
    js: banner,
  },
  entryPoints: [
    './src/main.ts',
    './src/styles.scss'
  ],
  bundle: true,
  external: [
    'obsidian',
    'electron',
    'tslib',
    '@codemirror/collab',
    '@codemirror/commands',
    '@codemirror/language',
    '@codemirror/lint',
    '@codemirror/search',
    '@codemirror/state',
    '@codemirror/view',
    '@lezer/common',
    '@lezer/highlight',
    '@lezer/lr',
    ...builtins
  ],
  format: 'cjs',
  target: 'es2018',
  logLevel: 'info',
  sourcemap: prod ? false : 'inline',
  treeShaking: true,
  define: {
    'process.env.NODE_ENV': prod ? '"production"' : '"development"',
  },
  // No keepNames: the DI container resolves services by stable symbol tokens
  // (see `@Inject(TOKENS.x)` and `LineChangeTrackerPlugin.get`), never by
  // `constructor.name`. Tokens survive minification untouched, so the bundle can
  // freely rename/mangle class identifiers without breaking resolution.
  plugins: [sassPlugin({
    basedir: './',
    cssOutfile: './styles.css',
    type: 'css',
  })],
  outdir: './',
});

if (prod) {
  await context.rebuild();
  process.exit(0);
} else {
  await context.watch();
}
