import esbuild from 'esbuild';
import process from 'process';
import path from 'node:path';
import { builtinModules } from 'node:module';
import { sassPlugin } from '@shellscape/esbuild-sass-plugin';

// Routes diff2html's `require('@profoundlogic/hogan')` to a render-only stub
// so hogan's template compiler (it assembles templates via `new Function`)
// never enters the bundle; the plugin ships precompiled templates instead
// (src/vendor/diff2html-templates.gen.ts). The exact-match filter keeps the
// stub's own deep import of hogan's Template runtime resolving into the real
// package.
const hoganStubPlugin = {
  name: 'hogan-stub',
  setup(build) {
    build.onResolve({ filter: /^@profoundlogic\/hogan$/ }, () => ({
      path: path.resolve('./src/vendor/hogan.stub.ts'),
    }));
  },
};

const banner =
  `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === 'production');

const context = await esbuild.context({
  banner: {
    js: banner,
  },
  entryPoints: [
    './src/main.ts',
    './src/styles.scss'
  ],
  bundle: true,
  external: [
    'obsidian',
    'electron',
    'tslib',
    '@codemirror/collab',
    '@codemirror/commands',
    '@codemirror/language',
    '@codemirror/lint',
    '@codemirror/search',
    '@codemirror/state',
    '@codemirror/view',
    '@lezer/common',
    '@lezer/highlight',
    '@lezer/lr',
    ...builtinModules
  ],
  format: 'cjs',
  target: 'es2018',
  logLevel: 'info',
  sourcemap: prod ? false : 'inline',
  treeShaking: true,
  define: {
    'process.env.NODE_ENV': prod ? '"production"' : '"development"',
  },
  // No keepNames: the DI container resolves services by stable symbol tokens
  // (see `@Inject(TOKENS.x)` and `LineChangeTrackerPlugin.get`), never by
  // `constructor.name`. Tokens survive minification untouched, so the bundle can
  // freely rename/mangle class identifiers without breaking resolution.
  plugins: [hoganStubPlugin, sassPlugin({
    basedir: './',
    cssOutfile: './styles.css',
    type: 'css',
  })],
  outdir: './',
});

if (prod) {
  await context.rebuild();
  process.exit(0);
} else {
  await context.watch();
}
